apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mallow-sale-ingress
  namespace: mallow-sale
  annotations:
    nginx.ingress.kubernetes.io/app-root: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: mallow-sale-api-service
                port:
                  number: 4000
